Arguments: 
  /usr/local/Cellar/node/9.6.1/bin/node /usr/local/Cellar/yarn/1.5.1/libexec/bin/yarn.js start

PATH: 
  /Users/acarriger/.rvm/gems/ruby-2.4.1/bin:/Users/acarriger/.rvm/gems/ruby-2.4.1@global/bin:/Users/acarriger/.rvm/rubies/ruby-2.4.1/bin:./bin:/usr/local/bin:/usr/local/sbin:/Users/acarriger/.dotfiles/bin:/Users/acarriger/.nvm/versions/node/v8.10.0/bin:/Users/acarriger/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/bin:/Users/acarriger/.rvm/bin

Yarn version: 
  1.5.1

Node version: 
  9.6.1

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "1",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1",
      "start": "npm run dev",
      "dev": "(cd src && ws)"
    },
    "author": "Adrian Carriger",
    "license": "MIT",
    "devDependencies": {
      "local-web-server": "^2.6.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c npm run dev
  Directory: /Users/acarriger/open-source/experiments/v/2
  Output:
  
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:127:13)
      at maybeClose (internal/child_process.js:933:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
